#!/usr/bin/env bash

dir=$(cd `dirname $0`; pwd)
function link()
{
    path=$1
    from_path=$dir/$path
    to_path=$HOME/$path
    if [ -e $from_path -a ! -d $to_path -a ! -f $to_path ]; then
        if [[ $1 != ".xinitrc" || `uname` != 'Darwin' ]]; then
            echo "link $from_path to $to_path"
            ln -s $from_path $to_path
        fi
    else
        echo "WARNNING: $to_path exists"
    fi
}

link_files=('.bashrc' '.zshrc' '.tmux.conf' '.xinitrc' '.bash_profile' '.emacs' '.emacs.d' '.spacemacs')

for f in ${link_files[@]}
do
    echo $f
    link $f
done

if [[ `uname` == 'Darwin' ]]; then
    link .pydistutils.cfg
fi

test -e $HOME/.lein/profiles.clj || ln -s $dir/profiles.clj $HOME/.lein/profiles.clj
